apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: slimy-rodent-java-springboot
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:435529efd8c3a04d5b3b36bea8b4d5f3c5d5c152@sha256:816335d0723c3c5c10ec33a046e2d04a79503d57e7eb2eecaa2ea55c7c68a80c
        name: container-image  
